<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNy361kl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNy361kl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNy361kl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNy361kl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNy361kl\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ny361kl',
    'container.build_id' => '8ee3cd12',
    'container.build_time' => 1668668629,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNy361kl');
